from launcher.ui_launcher import Ui_MainWindow
from dashboard.ui_dashoboard import Ui_dashboard
from alert.ui_alert_dialog import Ui_AlertDialog
from database.ui_program_dept import Ui_Database
from registration.ui_registration import Ui_Registration